export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

export const GET_PEDIDOS = 'GET_PEDIDOS'
export const GET_PEDIDO = 'GET_PEDIDO'
export const CANCELAR_PEDIDO = 'CANCELAR_PEDIDO'
export const LIMPAR_PEDIDO = 'LIMPAR_PEDIDO'

export const GET_CLIENTES = 'GET_CLIENTES'
export const LIMPAR_CLIENTE = "LIMPAR_CLIENTE"
export const GET_CLIENTE = "GET_CLIENTE"
export const GET_CLIENTE_PEDIDOS = "GET_CLIENTE_PEDIDOS"
export const REMOVE_CLIENTE = "REMOVE_CLIENTE"

export const GET_CATEGORIA = "GET_CATEGORIA"
export const GET_CATEGORIAS = "GET_CATEGORIAS"
export const LIMPAR_CATEGORIA = "LIMPAR_CATEGORIA"
export const REMOVE_CATEGORIA = "REMOVE_CATEGORIA"
export const GET_CATEGORIA_PRODUTOS = "GET_CATEGORIA_PRODUTOS"

export const GET_PRODUTOS = "GET_PRODUTOS"
export const GET_PRODUTO = "GET_PRODUTO"